# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'Default'

variables:
   imageName: 'pipelines-javascript-docker'
   repositoryName: 'azharpasha'
   dockerTag: '$(Build.BuildId)'

steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     repository: '$(repositoryName)/$(imageName)'
     command: build
     Dockerfile: 'Dockerfile'
     tags: |
      $(dockerTag)

 - task: Docker@2
   displayName: push the image
   inputs:
     containerRegistry: 'project-cicd'
     repository: '$(repositoryName)/$(imageName)'
     command: push
     tags: |
      $(dockerTag)
     
    
     

